// <auto-generated />
using System;
using AppExtensionista.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppExtensionista.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919193857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("AppExtensionista.Models.AlimentoModel", b =>
                {
                    b.Property<int>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ALIMENTO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ATIVO");

                    b.Property<int>("IdUsuarioCriador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO_CRIADOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.HasKey("IdAlimento");

                    b.HasIndex("IdUsuarioCriador");

                    b.ToTable("ALIMENTO");
                });

            modelBuilder.Entity("AppExtensionista.Models.EstoqueModel", b =>
                {
                    b.Property<int>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ESTOQUE");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_VALIDADE");

                    b.Property<string>("FormaArmazenamento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FORMA_ARMAZENAMENTO");

                    b.Property<int>("IdAlimento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ALIMENTO");

                    b.Property<int>("IdUsuarioCriador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO_CRIADOR");

                    b.Property<string>("LocalArmazenamento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LOCAL_ARMAZENAMENTO");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("QuantidadeOriginal")
                        .HasColumnType("TEXT")
                        .HasColumnName("QUANTIDADE_ORIGINAL");

                    b.HasKey("IdEstoque");

                    b.HasIndex("IdAlimento");

                    b.HasIndex("IdUsuarioCriador");

                    b.ToTable("ESTOQUE");
                });

            modelBuilder.Entity("AppExtensionista.Models.GuiaArmazenamentoModel", b =>
                {
                    b.Property<int>("IdGuiaArmazenamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_GUIA_ARMAZENAMENTO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_ULTIMA_ALTERACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("IdAlimento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ALIMENTO");

                    b.Property<int>("IdUsuarioResponsavel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO_RESPONSAVEL");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TITULO");

                    b.HasKey("IdGuiaArmazenamento");

                    b.HasIndex("IdAlimento");

                    b.HasIndex("IdUsuarioResponsavel");

                    b.ToTable("GUIA_ARMAZENAMENTO");
                });

            modelBuilder.Entity("AppExtensionista.Models.RegistroDescarteModel", b =>
                {
                    b.Property<int>("IdListaDescarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_LISTA_DESCARTE");

                    b.Property<DateTime>("DataDescarte")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_DESCARTE");

                    b.Property<string>("DescricaoMotivo")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO_MOTIVO");

                    b.Property<int>("IdEstoque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ESTOQUE");

                    b.Property<int>("IdUsuarioResponsavel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO_RESPONSAVEL");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("IdListaDescarte");

                    b.HasIndex("IdEstoque");

                    b.HasIndex("IdUsuarioResponsavel");

                    b.ToTable("REGISTRO_DESCARTE");
                });

            modelBuilder.Entity("AppExtensionista.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("DiasAlertaPadrao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DIAS_ALERTA_PADRAO");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("AppExtensionista.Models.AlimentoModel", b =>
                {
                    b.HasOne("AppExtensionista.Models.UsuarioModel", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCriador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("AppExtensionista.Models.EstoqueModel", b =>
                {
                    b.HasOne("AppExtensionista.Models.AlimentoModel", "Alimento")
                        .WithMany()
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppExtensionista.Models.UsuarioModel", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCriador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("AppExtensionista.Models.GuiaArmazenamentoModel", b =>
                {
                    b.HasOne("AppExtensionista.Models.AlimentoModel", "Alimento")
                        .WithMany()
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppExtensionista.Models.UsuarioModel", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("AppExtensionista.Models.RegistroDescarteModel", b =>
                {
                    b.HasOne("AppExtensionista.Models.EstoqueModel", "Estoque")
                        .WithMany()
                        .HasForeignKey("IdEstoque")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppExtensionista.Models.UsuarioModel", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("UsuarioResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
